#!/bin/bash

readarray PROGRAMS < ~/.auto-install-programs/programs-to-install
readarray PROGRAMS_USER_INTERACT < ~/.auto-install-programs/programs-to-install-require-user-interaction
readarray PROGRAMS_LONG < ~/.auto-install-programs/programs-to-install-long
readarray REPOS < ~/.auto-install-programs/repos-to-add

COMPLETED=()
FAILED=()

if [[ ${PROGRAMS_USER_INTERACT[@]} > 0 ]]
then
  echo "There are programs that are set to be installed that may require user interaction."
  echo "These programs will be installed first, so that this script can be left alone as soon as possible."
  echo " "
  echo "Install these programs [yN]? "
  read do_user_interaction
fi

if [[ ${PROGRAMS_LONG[@]} > 0 ]]
then
  echo "There are programs that are set to be installed that may take a significant amount of time to install"
  echo " "
  echo "Install these programs [yN]? "
  read do_long
fi

# add repositories
for REPO in ${REPOS[@]}
do
  echo "------------------------------------------------------------"
  echo "Adding Repository - $REPO"
  sudo add-apt-repository -y $REPO
  echo "------------------------------------------------------------"
done

echo "------------------------------------------------------------"
echo "Starting Update"
sudo apt-get -y update
echo "Update Completed"
echo "------------------------------------------------------------"
echo " "
echo " "


if [[ $do_user_interaction = "y" ||$do_user_interaction = "Y" ]]
then
  # This is for programs that may require user interaction
  for PROGRAM in ${PROGRAMS_USER_INTERACT[@]}
  do
    echo "------------------------------------------------------------"
    echo "Start Installation - $PROGRAM"
    sudo apt-get -y install $PROGRAM
    if [ $? -eq 0 ]
    then
      echo " "
      echo " "
      echo "Install COMPLETED Successfully - $PROGRAM"
      echo "------------------------------------------------------------"
      echo " "
      echo " "
      COMPLETED+=($PROGRAM)
    else
      echo " "
      echo " "
      echo "Install FAILED - $PROGRAM"
      echo "------------------------------------------------------------"
      echo " "
      echo " "
      FAILED+=($PROGRAM)
    fi
    echo "The programs that may have required user interaction are now installed!"
    read -p "Press [enter] to continue..."
  done
fi


if [[ $do_long = "y" ||$do_long = "Y" ]]
then
  # This is for programs that may require user interaction
  for PROGRAM in ${PROGRAMS_USER_INTERACT[@]}
  do
    echo "------------------------------------------------------------"
    echo "Start Installation - $PROGRAM"
    sudo apt-get -y install $PROGRAM
    if [ $? -eq 0 ]
    then
      echo " "
      echo " "
      echo "Install COMPLETED Successfully - $PROGRAM"
      echo "------------------------------------------------------------"
      echo " "
      echo " "
      COMPLETED+=($PROGRAM)
    else
      echo " "
      echo " "
      echo "Install FAILED - $PROGRAM"
      echo "------------------------------------------------------------"
      echo " "
      echo " "
      FAILED+=($PROGRAM)
    fi
    echo "The programs that may have required user interaction are now installed!"
    read -p "Press [enter] to continue..."
  done
fi


for PROGRAM in ${PROGRAMS[@]}
do
  echo "------------------------------------------------------------"
  echo "Start Installation - $PROGRAM"
  sudo apt-get -y install $PROGRAM
  if [ $? -eq 0 ]
  then
    echo " "
    echo " "
    echo "Install COMPLETED Successfully - $PROGRAM"
    echo "------------------------------------------------------------"
    echo " "
    echo " "
    COMPLETED+=($PROGRAM)
  else
    echo " "
    echo " "
    echo "Install FAILED - $PROGRAM"
    echo "------------------------------------------------------------"
    echo " "
    echo " "
    FAILED+=($PROGRAM)
  fi
done

#===================================================================================


echo "Programs that Successfully Installed"
echo "------------------------------------"
for PROGRAM in ${COMPLETED[@]}
do
  echo $PROGRAM
done
echo " "
echo "Programs that FAILED to Install"
echo "------------------------------------"
for PROGRAM in ${FAILED[@]}
do
  echo $PROGRAM
done
echo " "
