#!/bin/bash

readarray PROGRAMS < ~/.auto-install-programs/programs-to-install
readarray PROGRAMS_USER_INTERACT < ~/.auto-install-programs/programs-to-install-require-user-interaction
readarray REPOS < ~/.auto-install-programs/repos-to-add

COMPLETED=()
FAILED=()

if [[ ${PROGRAMS_USER_INTERACT[@]} > 0 ]]
then
  echo "There are programs that are set to be installed that may require user interaction."
  echo "These programs will be installed first, so that this script can be left alone as soon as possible."
  echo "Please stay at the computer until a Message displays that says you can. The script will pause for this..."
  read -p "Press [enter] to continue..."
fi

## add repositories
for REPO in ${REPOS[@]}
do
  echo "------------------------------------------------------------"
  echo "Adding Repository - $REPO"
  sudo add-apt-repository -y $REPO
  echo "------------------------------------------------------------"
done

echo "------------------------------------------------------------"
echo "Starting Update"
sudo apt-get -y update
echo "Update Completed"
echo "------------------------------------------------------------"
echo " "
echo " "


# This is for programs that may require user interaction
for PROGRAM in ${PROGRAMS_USER_INTERACT[@]}
do
  echo "------------------------------------------------------------"
  echo "Start Installation - $PROGRAM"
  sudo apt-get -y install $PROGRAM
  if [ $? -eq 0 ]
  then
    echo " "
    echo " "
    echo "Install COMPLETED Successfully - $PROGRAM"
    echo "------------------------------------------------------------"
    echo " "
    echo " "
    COMPLETED+=($PROGRAM)
  else
    echo " "
    echo " "
    echo "Install FAILED - $PROGRAM"
    echo "------------------------------------------------------------"
    echo " "
    echo " "
    FAILED+=($PROGRAM)
  fi
  echo "The programs that may have required user interaction are now installed!"
  read -p "Press [enter] to continue..."
done


for PROGRAM in ${PROGRAMS[@]}
do
  echo "------------------------------------------------------------"
  echo "Start Installation - $PROGRAM"
  sudo apt-get -y install $PROGRAM
  if [ $? -eq 0 ]
  then
    echo " "
    echo " "
    echo "Install COMPLETED Successfully - $PROGRAM"
    echo "------------------------------------------------------------"
    echo " "
    echo " "
    COMPLETED+=($PROGRAM)
  else
    echo " "
    echo " "
    echo "Install FAILED - $PROGRAM"
    echo "------------------------------------------------------------"
    echo " "
    echo " "
    FAILED+=($PROGRAM)
  fi
done

### Special Case Programs

#===================================================================================
# If the fuck already exists then just update it. if it does not then install
# it.
echo "------------------------------------------------------------"
echo "Start Installation - thefuck"
if [ -e /usr/local/bin/thefuck ]
then
  sudo pip install thefuck --upgrade
else
  sudo pip install thefuck
fi

if [ $? -eq 0 ]
then
  echo " "
  echo " "
  echo "Install COMPLETED Successfully - thefuck"
  echo "------------------------------------------------------------"
  echo " "
  echo " "
  COMPLETED+=(thefuck)
else
  echo " "
  echo " "
  echo "Install FAILED - thefuck"
  echo "------------------------------------------------------------"
  echo " "
  echo " "
  FAILED+=(thefuck)
fi
#===================================================================================


echo "Programs that Successfully Installed"
echo "------------------------------------"
for PROGRAM in ${COMPLETED[@]}
do
  echo $PROGRAM
done
echo " "
echo "Programs that FAILED to Install"
echo "------------------------------------"
for PROGRAM in ${FAILED[@]}
do
  echo $PROGRAM
done
echo " "
