#!/bin/bash

readarray PROGRAMS < ~/.auto-install-programs/programs-to-install
readarray REPOS < ~/.auto-install-programs/repos-to-add

COMPLETED=()
FAILED=()

## add repositories
for REPO in ${REPOS[@]}
do
  echo "------------------------------------------------------------"
  echo "Adding Repository - $REPO"
  sudo add-apt-repository -y $REPO
  echo "------------------------------------------------------------"
done

echo "------------------------------------------------------------"
echo "Starting Update"
sudo apt-get -y update
echo "Update Completed"
echo "------------------------------------------------------------"
echo " "
echo " "

for PROGRAM in ${PROGRAMS[@]}
do
  echo "------------------------------------------------------------"
  echo "Start Installation - $PROGRAM"
  sudo apt-get -y install $PROGRAM
  if [ $? -eq 0 ]
  then
    echo " "
    echo " "
    echo "Install COMPLETED Successfully - $PROGRAM"
    echo "------------------------------------------------------------"
    echo " "
    echo " "
    COMPLETED+=($PROGRAM)
  else
    echo " "
    echo " "
    echo "Install FAILED - $PROGRAM"
    echo "------------------------------------------------------------"
    echo " "
    echo " "
    FAILED+=($PROGRAM)
  fi
done

echo "Programs that Successfully Installed"
echo "------------------------------------"
for PROGRAM in ${COMPLETED[@]}
do
  echo $PROGRAM
done
echo " "
echo "Programs that FAILED to Install"
echo "------------------------------------"
for PROGRAM in ${FAILED[@]}
do
  echo $PROGRAM
done
echo " "
