#!/bin/bash

sudo mkdir -p /usr/share/texlive/texmf-dist/tex/latex/unicode-math/

cd ~/.latex-unicode-math

sudo cp * /usr/share/texlive/texmf-dist/tex/latex/unicode-math/

#Update Fonts
sudo fc-cache -f -v
sudo -H mktexlsr
