#!/bin/bash

DOTFILE_PATH="/home/steven/Documents/git-repos/remote-github/dotfiles"

cd ~/

ln -fs "$DOTFILE_PATH/.auto-clone/"
ln -fs "$DOTFILE_PATH/.vim"
ln -fs "$DOTFILE_PATH/.vimrc"
ln -fs "$DOTFILE_PATH/.bash_aliases"
ln -fs "$DOTFILE_PATH/.bash_profile"
ln -fs "$DOTFILE_PATH/.profile"
ln -fs "$DOTFILE_PATH/.bashrc"
ln -fs "$DOTFILE_PATH/.auto-install-programs/"
ln -fs "$DOTFILE_PATH/.detoxrc"
ln -fs "$DOTFILE_PATH/.fonts/"
ln -fs "$DOTFILE_PATH/.gitconfig"
ln -fs "$DOTFILE_PATH/.gnome2/"
ln -fs "$DOTFILE_PATH/.gvimrc"
ln -fs "$DOTFILE_PATH/.inputrc"
ln -fs "$DOTFILE_PATH/.my-scripts/"
ln -fs "$DOTFILE_PATH/update-all-repos"
ln -fs "$DOTFILE_PATH/custom-fortunes"
ln -fs "$DOTFILE_PATH/.gitradarrc"
ln -fs "$DOTFILE_PATH/.fetchmailrc"
ln -fs "$DOTFILE_PATH/.msmtprc"
ln -fs "$DOTFILE_PATH/.muttrc"
ln -fs "$DOTFILE_PATH/.procmailrc"
ln -fs "$DOTFILE_PATH/.tmux.conf"
ln -fs "$DOTFILE_PATH/.tmux_theme.sh"

## .config

cd ~/.config/
ln -sf "$DOTFILE_PATH/.config/fish/"
ln -sf "$DOTFILE_PATH/.config/sxiv"
ln -sf "$DOTFILE_PATH/.config/mpv"

cd ~/.config/caja
ln -fs "$DOTFILE_PATH/.config/caja/scripts"

# moc
mkdir -p ~/.moc
cd ~/.moc
ln -sf "$DOTFILE_PATH/.moc/config"
ln -sf "$DOTFILE_PATH/.moc/themes"
ln -sf "$DOTFILE_PATH/.moc/onsongchange"


mkdir -p ~/.config/ranger
cd ~/.config/ranger
ln -sf $DOTFILE_PATH/.config/ranger/rc.conf
ln -sf $DOTFILE_PATH/.config/ranger/scope.sh
