#!/bin/bash

DOTFILE_PATH=~/Documents/git-repos/remote-github/dotfiles

cd ~/

ln -s $DOTFILE_PATH/
ln -s $DOTFILE_PATH/.auto-clone/
ln -s $DOTFILE_PATH/.vim
ln -s $DOTFILE_PATH/.vimrc
ln -s $DOTFILE_PATH/.bash_aliases
ln -s $DOTFILE_PATH/.bash_profile
ln -s $DOTFILE_PATH/.bashrc
ln -s $DOTFILE_PATH/.auto-install-programs/
ln -s $DOTFILE_PATH/.detoxrc
ln -s $DOTFILE_PATH/.fonts/
ln -s $DOTFILE_PATH/.gitconfig
ln -s $DOTFILE_PATH/.gnome2/
ln -s $DOTFILE_PATH/.gvimrc
ln -s $DOTFILE_PATH/.inputrc
ln -s $DOTFILE_PATH/.my-scripts/
ln -s $DOTFILE_PATH/.profile
ln -s $DOTFILE_PATH/sym-link-files-to-home
ln -s $DOTFILE_PATH/update-all-repos
ln -s $DOTFILE_PATH/.XCompose

