#!/bin/bash

# Update ~/ with new pulled dotfiles
echo "Updating remote-github/dotfiles"
cd ~/Documents/git-repos/remote-github/dotfiles
git pull
./sym-link-files-to-home


cd ~/Documents/git-repos/remote-github

REPO_NAMES=(*)

for REPO in ${REPO_NAMES[@]}
do
  cd $REPO
  echo "Updating remote-github/${REPO}..."
  git pull
  cd ..
done


cd ~/Documents/git-repos/repos-i-contribute-to

REPO_NAMES=(*)

for REPO in ${REPO_NAMES[@]}
do
  cd $REPO
  echo "Updating repos-i-contribute-to/${REPO}..."
  git pull
  cd ..
done

cd ~/Documents/git-repos/useful-repos

REPO_NAMES=(*)

for REPO in ${REPO_NAMES[@]}
do
  cd $REPO
  echo "Updating useful-repos/${REPO}..."
  git pull
  cd ..
done

