#!/bin/bash

# Update ~/ with new pulled dotfiles
echo "Updating remote-github/dotfiles"
# Try to go to this directory... If it fails, exit the script
cd ~/Documents/git-repos/remote-github/dotfiles || exit
git pull
./sym-link-files-to-home

function updateRepo {
  # if $1 is empty, exit
  if [ -z "$1" ]; then
    echo "Function updateRepo() expects 1 argument"
    exit
  fi

  cd "$1" || exit

  REPO_NAMES=(*)

  for REPO in "${REPO_NAMES[@]}"
  do
    cd $REPO || exit
    echo "Updating $1/${REPO}..."
    git pull
    cd ..
  done
}



updateRepo "$REPOS/remote-github"
updateRepo "$REPOS/repos-i-contribute-to"
updateRepo "$REPOS/useful-repos"
updateRepo "$dotfiles/.submodules"
