#!/bin/bash

cd ~
git pull origin master
if [ "$1" = "--install" ]
then
  .auto-install-programs/install-programs
fi

if [ -d ~/Documents/git-repos/vim-repos ]
then
  ./update-vim-plugins
fi
./create-sym-links-for-myscripts
custom-fortunes/install-quote
