#!/bin/bash

echo " " ;
echo "==========================================="
echo "Ready to Update..."

echo "OS is $OS"
if [[ $OS  == "Debian" ]]; then
  sudo apt-get update
  sudo apt-get -y dist-upgrade
elif [[ $OS  == "Manjaro" &&
        $OS  == "Arch"
     ]]; then
  sudo pacman -Syyu --noconfirm
else
  echo "Could not determine what package manager to use."
  exit 1
fi

echo " "
echo "Update Complete!"
echo "==========================================="
