#!/bin/bash

echo " " ;
echo "==========================================="
echo "Ready to Update..."
read -p "Press Enter to start the update..."
sudo apt-get dist-upgrade
echo "Updating thefuck now..."
sudo pip install thefuck --upgrade
echo " "
echo "Update Complete!"
echo "==========================================="
read -p "Press enter to exit the terminal."
