#!/bin/bash

readarray REPOS < ~/.auto-clone/my-repos-to-clone.cfg

mkdir -p ~/Documents/git-repos/remote-github/
cd ~/Documents/git-repos/remote-github/

## clone repositories
for REPO in "${REPOS[@]}"
do
  # Skip comments when parsing
  [[ ${REPO:0:1} == "#" ]] && continue
  # Skip empty lines when parsing
  [[ ${REPO:1:1} == "" ]] && continue

  echo "------------------------------------------------------------"
  echo "Cloning Repository - $REPO"
  git clone "$REPO"
  echo "------------------------------------------------------------"
done

readarray REPOS < ~/.auto-clone/contributing-repos-to-clone.cfg

mkdir -p ~/Documents/git-repos/repos-i-contribute-to
cd ~/Documents/git-repos/repos-i-contribute-to

## clone repositories
for REPO in "${REPOS[@]}"
do
  # Skip comments when parsing
  [[ ${REPO:0:1} == "#" ]] && continue
  # Skip empty lines when parsing
  [[ ${REPO:1:1} == "" ]] && continue

  echo "------------------------------------------------------------"
  echo "Cloning Repository - $REPO"
  git clone "$REPO"
  echo "------------------------------------------------------------"
done

readarray REPOS < ~/.auto-clone/useful-repos-to-clone.cfg

mkdir -p ~/Documents/git-repos/useful-repos
cd ~/Documents/git-repos/useful-repos

## clone repositories
for REPO in "${REPOS[@]}"
do
  # Skip comments when parsing
  [[ ${REPO:0:1} == "#" ]] && continue
  # Skip empty lines when parsing
  [[ ${REPO:1:1} == "" ]] && continue

  echo "------------------------------------------------------------"
  echo "Cloning Repository - $REPO"
  git clone "$REPO"
  echo "------------------------------------------------------------"
done


echo " "
