#!/bin/bash

readarray REPOS < ~/.auto-clone/my-repos-to-clone

mkdir -p ~/Documents/git-repos/remote-github/
cd ~/Documents/git-repos/remote-github/

## clone repositories
for REPO in ${REPOS[@]}
do
  echo "------------------------------------------------------------"
  echo "Cloning Repository - $REPO"
  git clone $REPO
  echo "------------------------------------------------------------"
done

readarray REPOS < ~/.auto-clone/contributing-repos-to-clone

mkdir -p ~/Documents/git-repos/remote-github/repos-i-contribute-to
cd ~/Documents/git-repos/remote-github/repos-i-contribute-to

## clone repositories
for REPO in ${REPOS[@]}
do
  echo "------------------------------------------------------------"
  echo "Cloning Repository - $REPO"
  git clone $REPO
  echo "------------------------------------------------------------"
done

readarray REPOS < ~/.auto-clone/useful-repos-to-clone

mkdir -p ~/Documents/git-repos/remote-github/useful-repos
cd ~/Documents/git-repos/remote-github/useful-repos

## clone repositories
for REPO in ${REPOS[@]}
do
  echo "------------------------------------------------------------"
  echo "Cloning Repository - $REPO"
  git clone $REPO
  echo "------------------------------------------------------------"
done


echo " "
