#!/bin/bash

if [ -n "$1" ] && { [ "$1" = "--seconds" ] || [ "$1" = "-s" ] ; }; then
    code='
        print (HR * 3600) + (MIN * 60) + SEC
    ';
    shift
else
    code='
        HR  = (HR == 0)              ? "" : (HR+0 "h ")
        MIN = (HR == "" && MIN == 0) ? "" : (MIN+0 "m ")

        print HR MIN SEC+0 "s"
    ';
fi

for file in "$@"; do
    echo "$file";
    ffmpeg -i "$file" 2>&1 | awk -F'[ ,:]+' "
        \$2 == \"Duration\" {
            HR  = \$3;
            MIN = \$4;
            SEC = \$5;

            $code
        }
    ";
    echo ""
done
