#!/bin/bash

# Emoji Manager

normalizeString() {
    echo "$1" | tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
}

char2emoji() {
    local letter="$1";
    local offset;
    local a_ascii=65
    local idx;
    local a_emoji=0x1F1E6;

    if [ "$letter" = " " ]; then
        # Space, so add additional spaces to help separate the emojis
        echo "   ";
        return;
    elif [ "$letter" = "?" ]; then
        echo "\U00002754";
        return;
    elif [ "$letter" = "!" ]; then
        echo "\U00002755";
        return;
    elif ! echo "$letter" | grep -q "^[A-Z]$"; then
        echo "$letter";
        return;
    fi

    offset="$(printf "%d" "'$letter")";

    idx=$((offset-a_ascii))

    printf "\\\U000%x" "$((a_emoji+idx))"
}

emojify() {
    local string="$1"
    local char;
    local ret="";

    string="$(normalizeString "$string")"

    for (( i=1; i<=${#string}; i++ )); do
        char="$(printf '%s\n' "$string" | cut -c${i})"

        ret="${ret} $(char2emoji "$char")"
    done

    echo -e "$ret"
}

emojis="$(cat <<EOF
Emojify String

angry livid mad             - 😠
check correct tick          - ✔
confused                    - 😕
cross wrong x               - ❌
crying                      - 😢
disappointed sad            - 😞
drooling                    - 🤤
exclamation mark            - ❕
facepalm                    - 🤦
fingers crossed             - 🤞
fist bump                   - 🤜🤛
fist bump distance          - 🤜        🤛
laugh cry                   - 😂
loudly crying               - 😭
middle finger               - 🖕
ok okay perfect             - 👌
pointing down               - 👇
pointing up                 - 👆
poop                        - 💩
question mark               - ❔
sleep zzz boring tired      - 💤
thumbs down                 - 👎
thumbs up                   - 👍
vulcan salute greetings     - 🖖

canada flag                 - 🇨🇦
united kingdom flag         - 🇬🇧
united states american flag - 🇺🇸

confused                    - 「(°ヘ°)
confused shrug              - ¯\(°_o)/¯
crying                      - ༼ ༎ຶ ෴ ༎ຶ༽
flipping table              - (╯°□°）╯︵ ┻━┻
happy                       - (✿◠‿◠)
i see what you did there    - (͡° ͜ʖ ͡°)
middle finger               - (凸ಠ益ಠ)凸
shifty eyes                 - (¬､¬)
shrug                       - ¯\_(ツ)_/¯
surprised                   - (ﾉﾟ0ﾟ)ﾉ

degrees                     - °
EOF
)"

choice="$(echo -e "$emojis" | dmenu -i -l 20 -c)";

if [ "$choice" = "" ]; then
    exit 0;
elif [ "$choice" = "Emojify String" ]; then
    string="$(echo "" | dmenu -c -i -p "Enter a String: ")";

    if [ "$string" = "" ]; then
        exit 0;
    fi

    toCopy="$(emojify "$string")"
else
    toCopy="$(echo "$choice" | awk -F' *- *' '{ print $2 }')";
fi

echo "$toCopy" | tr -d "\n" | xclip -sel clip;
