#!/bin/bash

fetchSucceeded() {
    err -s "Git Fetch has Finished!"
}

fetchFailed() {
    err -e "Git Fetch Failed!"
}

preFetch() {
    err -s "Fetching from Git"
}

preFetchFailed() {
    err -e "Pre Fetch Command Failed"
}

main() {
    local opt="$1"

    if [ "$opt" = "fetch_succeeded" ]; then
        # The fetch command ran and succeeded
        fetchSucceeded
        return $?
    elif [ "$opt" = "fetch_failed" ]; then
        # The fetch command ran but it failed
        fetchFailed
        return $?
    elif [ "$opt" = "pre_fetch" ]; then
        # We want to do a fetch. This is to setup the fetch and do any
        # preprocessing
        preFetch
        return $?
    elif [ "$opt" = "pre_fetch_failed" ]; then
        # The pre fetch ran but failed
        preFetchFailed
        return $?
    else
        err -e "No such option '$opt'"
        return 1
    fi
}

main "$@"
exit $?
