#!/bin/bash

CWD="$(pwd)"

recurse=0
if [ "$1" = "recurse" ]; then
    recurse=1
fi

find . -type d | while read -r dir; do
    if [ "$dir" = '.' ]; then
        continue
    fi

    if ! cd "$dir"; then
        echo "dir '$dir' doesn't exist"
        exit 1
    fi

    if [ "$recurse" -eq 1 ]; then
        count="$(find . -type f | wc -l)"
    else
        count="$(find . -maxdepth 1 -type f | wc -l)"
    fi

    echo "$count $dir"

    if ! cd "$CWD"; then
        echo "cwd '$CWD' doesn't exist."
        exit 1
    fi
done | sort -nr | head -"${1:-1}"
